// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKNlbUdvbNZHHWNgDPT1GCa1jKptRfXVA',
    appId: '1:522749971258:web:afaa2c524a9a25e31dde03',
    messagingSenderId: '522749971258',
    projectId: 'vaultly-d1081',
    authDomain: 'vaultly-d1081.firebaseapp.com',
    storageBucket: 'vaultly-d1081.firebasestorage.app',
    measurementId: 'G-HH8N6FC82Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWleS7oyKca2QyfSuNsnMc73Rw-DDxPpg',
    appId: '1:522749971258:android:2543844db3b243531dde03',
    messagingSenderId: '522749971258',
    projectId: 'vaultly-d1081',
    storageBucket: 'vaultly-d1081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9aTkcGy_p9WOfxqTjv2rCTQR1LXIJeFM',
    appId: '1:522749971258:ios:953f99698739790a1dde03',
    messagingSenderId: '522749971258',
    projectId: 'vaultly-d1081',
    storageBucket: 'vaultly-d1081.firebasestorage.app',
    iosClientId: '522749971258-pugokq7o8mofu1pi68ft07uiik02ug9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.vaultly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9aTkcGy_p9WOfxqTjv2rCTQR1LXIJeFM',
    appId: '1:522749971258:ios:953f99698739790a1dde03',
    messagingSenderId: '522749971258',
    projectId: 'vaultly-d1081',
    storageBucket: 'vaultly-d1081.firebasestorage.app',
    iosClientId: '522749971258-pugokq7o8mofu1pi68ft07uiik02ug9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.vaultly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKNlbUdvbNZHHWNgDPT1GCa1jKptRfXVA',
    appId: '1:522749971258:web:a4b2558056c7b7d11dde03',
    messagingSenderId: '522749971258',
    projectId: 'vaultly-d1081',
    authDomain: 'vaultly-d1081.firebaseapp.com',
    storageBucket: 'vaultly-d1081.firebasestorage.app',
    measurementId: 'G-4Z4JJM44SH',
  );
}
